In [37]:
import numpy as np
from keras.datasets import mnist

(X_train, y_train), (X_test, y_test) = mnist.load_data()

[5 0 4 ... 5 6 8]


In [39]:
print(y_train[0])
for i in range(X_train[0].shape[0]):
    for j in range(X_train[0].shape[1]):
        print(f"{X_train[0][i, j]:3d}", end="")
    print()

import cv2
cv2.imwrite(f"./mnist-{y_train[0]}.jpg", X_train[0])

5
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  3 18 18 18126136175 26166255247127  0  0  0  0
  0  0  0  0  0  0  0  0 30 36 94154170253253253253253225172253242195 64  0  0  0  0
  0  0  0  0  0  0  0 49238253253253253253253253253251 93 82 82 56 39  0  0  0  0  0
  0  0  0  0  0  0  0 18219253253253253253198182247241  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0 80156107253253205 11  0 43154  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0 14  1154253 90  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0139253190  2  0  0  0  0  0  0

True

# LeNet 만들기
## 데이터 전처리하기
### 읽은 데이터를 reshape 후 정규화 해주기

In [40]:
import tensorflow as tf
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten
from keras.layers.convolutional import Conv2D, MaxPooling2D


data_cnt, row, col = X_train.shape
X_train = X_train.reshape(data_cnt, row, col, 1)
X_test = X_test.reshape(X_test.shape[0], row, col, 1)

X_train = X_train.astype('float32') / 255.
X_test = X_test.astype('float32') / 255.

정답 데이터를 범주형으로 바꿔주기

In [41]:
import keras

print(y_train)

num_classes = 10
y_train = keras.utils.to_categorical(y_train, num_classes)
y_test = keras.utils.to_categorical(y_test, num_classes)

print(y_train)

[[0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]]


In [43]:
model = Sequential()
model.add(Conv2D(32, kernel_size=(5, 5), strides=(1, 1), padding='same',
                 activation='tanh',
                 input_shape=(row, col, 1)))
model.add(MaxPooling2D(pool_size=(2, 2), strides=(2, 2)))
model.add(Conv2D(16, (10, 10), activation='tanh', padding='same'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Flatten())
model.add(Dense(120, activation='tanh'))
model.add(Dense(84, activation='tanh'))
model.add(Dense(num_classes, activation='softmax'))
model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_4 (Conv2D)           (None, 28, 28, 32)        832       
                                                                 
 max_pooling2d_4 (MaxPooling  (None, 14, 14, 32)       0         
 2D)                                                             
                                                                 
 conv2d_5 (Conv2D)           (None, 14, 14, 16)        51216     
                                                                 
 max_pooling2d_5 (MaxPooling  (None, 7, 7, 16)         0         
 2D)                                                             
                                                                 
 flatten_2 (Flatten)         (None, 784)               0         
                                                                 
 dense_3 (Dense)             (None, 120)              

In [45]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X_train, y_train,
                 batch_size=32,
                 epochs=10,
                 verbose=1, 
                 validation_data=(X_test, y_test))

Epoch 1/10
1875/1875 [==============================] - 96s 51ms/step - loss: 0.0941 - accuracy: 0.9719 - val_loss: 0.0631 - val_accuracy: 0.9791
Epoch 2/10
1875/1875 [==============================] - 103s 55ms/step - loss: 0.0487 - accuracy: 0.9856 - val_loss: 0.0421 - val_accuracy: 0.9853
Epoch 3/10
1875/1875 [==============================] - 99s 53ms/step - loss: 0.0356 - accuracy: 0.9889 - val_loss: 0.0391 - val_accuracy: 0.9872
Epoch 4/10
1875/1875 [==============================] - 91s 48ms/step - loss: 0.0279 - accuracy: 0.9908 - val_loss: 0.0563 - val_accuracy: 0.9829
Epoch 5/10
1875/1875 [==============================] - 92s 49ms/step - loss: 0.0241 - accuracy: 0.9926 - val_loss: 0.0439 - val_accuracy: 0.9870
Epoch 6/10
1875/1875 [==============================] - 89s 47ms/step - loss: 0.0221 - accuracy: 0.9927 - val_loss: 0.0424 - val_accuracy: 0.9869
Epoch 7/10
1875/1875 [==============================] - 88s 47ms/step - loss: 0.0191 - accuracy: 0.9937 - val_loss: 0.0411 

AttributeError: 'Sequential' object has no attribute 'score'

In [46]:
score = model.evaluate(X_test, y_test)
print(f"loss {score[0]} Accuracy {score[1]}")

313/313 [==============================] - 3s 11ms/step - loss: 0.0454 - accuracy: 0.9874
loss 0.04539415240287781 Accuracy 0.9873999953269958
